In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.4.1


In [5]:
arr = np.array([1, 2, 3, 4, 5])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
#0D array
arr0 = np.array(42)
print("0D array:", arr0)

0D array: 42


In [8]:
#1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

1D array: [1 2 3 4 5]


In [10]:
#check dimension
print(arr1.ndim)

1


In [11]:
#slicing 
print(arr1[1:5])


[2 3 4 5]


In [12]:
#dtype
print(arr1.dtype)

int64


In [13]:
#string
arr2 = np.array(['apple', 'banana', 'cherry'])

In [14]:
print(arr2.dtype)

<U6


In [15]:
print(arr1.dtype)

int64


In [16]:
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [17]:
print(arr.shape)

(5,)


In [18]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr4.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
#flattening the array
newarr = arr4.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
ar = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in ar:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [23]:
ar = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(ar):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [24]:
#random

In [25]:
from numpy import random
x = random.randint(100)
print(x)

43


In [26]:
x=random.randint(100, size=(5))

In [27]:
print(x)

[21 39 33  1 50]


In [28]:
np.arange(4, 20, 3)

array([ 4,  7, 10, 13, 16, 19])

In [30]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
#The NumPy.linspace() function returns an array of evenly spaced values within the specified interval [start, stop].

np.linspace(1, 10, 5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
#The eye tool returns a 2-D array with 1’s as the diagonal and 0’s elsewhere.
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = v1 + v2
print(v3)

[5 7 9]


In [34]:
#raveling arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.ravel()
print(newarr)

[1 2 3 4 5 6]


In [35]:
#transpose 
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.T
print(newarr)

[[1 4]
 [2 5]
 [3 6]]


In [36]:
#np.where() function is used to return the indices of elements in an input array where the given condition is satisfied.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [37]:
#np.extract() function is used to extract elements from an array based on a specified condition.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = np.extract(arr % 2 == 0, arr)
print(x)

[2 4 6 8]


In [38]:
#np.take() function is used to return elements from an array at specified indices.
arr = np.array([10, 20, 30, 40, 50])
x = np.take(arr, [0, 2, 4])
print(x)

[10 30 50]


In [39]:
#vectorised calculations
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a + b
print(c)

[11 22 33 44]
